// <auto-generated />
using System;
using DBOperationsWithEFCoreApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DBOperationsWithEFCoreApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DBOperationsWithEFCoreApi.Data.Book", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("createdOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<long>("languageId")
                        .HasColumnType("bigint");

                    b.Property<long>("noOfPages")
                        .HasColumnType("bigint");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("languageId");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("DBOperationsWithEFCoreApi.Data.BookPrice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CurrencyId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("bookId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("BookPrice");
                });

            modelBuilder.Entity("DBOperationsWithEFCoreApi.Data.Currency", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Currencies");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            currency = "INR",
                            description = "Indian Rupees"
                        },
                        new
                        {
                            Id = 2L,
                            currency = "USD",
                            description = "American Dollor"
                        },
                        new
                        {
                            Id = 3L,
                            currency = "EUR",
                            description = "Europian Currency"
                        },
                        new
                        {
                            Id = 4L,
                            currency = "JPY",
                            description = "Japanese Yen"
                        });
                });

            modelBuilder.Entity("DBOperationsWithEFCoreApi.Data.Language", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            description = "Hindi",
                            title = "Hindi"
                        },
                        new
                        {
                            Id = 2L,
                            description = "Punjabi",
                            title = "Punjabi"
                        },
                        new
                        {
                            Id = 3L,
                            description = "Kannada",
                            title = "Kannada"
                        },
                        new
                        {
                            Id = 4L,
                            description = "Odia",
                            title = "Odia"
                        });
                });

            modelBuilder.Entity("DBOperationsWithEFCoreApi.Data.Book", b =>
                {
                    b.HasOne("DBOperationsWithEFCoreApi.Data.Language", "language")
                        .WithMany("Books")
                        .HasForeignKey("languageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("language");
                });

            modelBuilder.Entity("DBOperationsWithEFCoreApi.Data.Language", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
